name: spicy_components
description: SpicyUI material components
version: 0.0.1
author: HrX03
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animations:

dev_dependencies:
  flutter_test:
    sdk: flutter
    
flutter: